#version: "3.9"

services:
  agent-core:
    build:
      context: ./agent_core
      dockerfile: Dockerfile
    container_name: agent-core
    env_file: ./agent_core/.env
    ports:
      - "${AGENT_CORE_PORT}:8004"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8004/v1/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - matprop_net
  agents:
      build:
        context: ./agents
        dockerfile: Dockerfile
      container_name: agents
      env_file: .env
      ports:
        - "${AGENTS_PORT}:8003"
      restart: unless-stopped
      volumes:
        - ollama_data:/root/.ollama
      depends_on:
        - agent-core
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8003/v2/health || exit 1"]
        interval: 30s
        timeout: 5s
        retries: 3
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
      networks:
        - matprop_net

  #backend-ml:
  #  build:
  #    context: ./backend_ml
  #    dockerfile: Dockerfile
  #  container_name: backend-ml
  #  env_file: .env
  #  ports:
  #    - "${BACKEND_ML_PORT}:8000"
  #  volumes:
  #    - ./backend_ml/src/data:/app/data:ro
  #    - ./backend_ml/src:/app/src:ro
  #  depends_on:
  #    - llm-model
  #  restart: unless-stopped
  #  healthcheck:
  #    test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
  #    interval: 30s
  #    timeout: 5s
  #    retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:8004"
        INTERNAL_API_URL: "http://agent-core:8004"
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8004"
      INTERNAL_API_URL: "http://agent-core:8004"
    depends_on:
      - agent-core
    networks:
      - matprop_net

networks:
  matprop_net:
    driver: bridge


volumes:
  ollama_data:
